networks:
  ai-agent:
    driver: bridge

services:

  # ===================== PostgreSQL =====================
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${HOME}/docker/pgvector/data:/var/lib/postgresql/data
      - ${PWD}/pgvector/table.sql:/docker-entrypoint-initdb.d/table.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== MySQL =====================
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${HOME}/docker/mysql/data:/var/lib/mysql
      - ${HOME}/docker/mysql/conf:/etc/mysql/conf.d:ro
      - ${HOME}/docker/mysql/logs:/logs
      - ${PWD}/mysql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== Redis =====================
  redis:
    image: redis:8.0.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - ${HOME}/docker/redis/data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== One-API =====================
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      TZ: ${TZ}
      SQL_DSN: ${ONEAPI_DB_USER}:${ONEAPI_DB_PASS}@tcp(mysql:3306)/${ONEAPI_DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    networks:
      - ai-agent

#  # ===================== Ollama =====================
#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    restart: unless-stopped
#    volumes:
#      - ${HOME}/docker/ollama:/root/.ollama
#    ports:
#      - "11434:11434"
#    networks:
#      - ai-agent
