networks:
  ai-agent:
    driver: bridge

services:

  # ===================== PostgreSQL =====================
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${HOME}/docker/pgvector/data:/var/lib/postgresql/data
      - ${PWD}/pgvector/table.sql:/docker-entrypoint-initdb.d/table.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== MySQL =====================
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${HOME}/docker/mysql/data:/var/lib/mysql
      - ${HOME}/docker/mysql/conf:/etc/mysql/conf.d:ro
      - ${HOME}/docker/mysql/logs:/logs
      - ${PWD}/mysql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== Redis =====================
  redis:
    image: redis:8.0.1
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - ${HOME}/docker/redis/data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== One-API =====================
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    platform: linux/amd64
    restart: always
    ports:
      - "3001:3000"
    environment:
      TZ: ${TZ}
      SQL_DSN: ${ONEAPI_DB_USER}:${ONEAPI_DB_PASS}@tcp(mysql:3306)/${ONEAPI_DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    networks:
      - ai-agent

  elasticsearch:
    image: elasticsearch:7.17.28
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ${HOME}/docker/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - ai-agent

  logstash:
    image: logstash:7.17.28
    container_name: logstash
    restart: always
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
      TZ: ${TZ}
      pipeline.ecs_compatibility: disabled
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - '9600:9600'
      - '50000:50000/tcp'
    depends_on:
      - elasticsearch
    networks:
      - ai-agent

  kibana:
    image: kibana:7.17.28
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - ai-agent

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ${HOME}/docker/prometheus/data:/prometheus
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - ai-agent

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ${HOME}/docker/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ai-agent

  grafana-mcp:
    image: mcp/grafana
    container_name: grafana-mcp
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    depends_on:
      - grafana
    networks:
      - ai-agent

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - ${PWD}/node-exporter:/host/tmp:ro
    command:
      - "--collector.textfile.directory=/host/tmp"
    networks:
      - ai-agent

#  # ===================== Ollama =====================
#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    restart: unless-stopped
#    volumes:
#      - ${HOME}/docker/ollama:/root/.ollama
#    ports:
#      - "11434:11434"
#    networks:
#      - ai-agent
