services:
  # ===================== MySQL =====================
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    depends_on:
      - pgvector
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${PASSWORD} --silent"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== Redis =====================
  redis:
    image: redis:8.0.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --appendonly
      - "yes"
      - --requirepass
      - ${PASSWORD}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${PASSWORD}", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== PostgreSQL =====================
  pgvector:
    image: pgvector/pgvector:0.7.4-pg16
    container_name: pgvector
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai-agent
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      TZ: ${TZ}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./pgvector/table.sql:/docker-entrypoint-initdb.d/table.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U ${USERNAME} -d ai-agent" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ai-agent

  # ===================== One-API =====================
  one-api:
    image: justsong/one-api:v0.6.11-preview.7
    container_name: one-api
#    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      SQL_DSN: ${USERNAME}:${PASSWORD}@tcp(mysql:3306)/oneapi?charset=utf8mb4&parseTime=True&loc=Local
      TZ: ${TZ}
    volumes:
      - oneapi_data:/data
    depends_on:
      - mysql
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ai-agent

  # ===================== MCP Servers =====================
  mcp-server-csdn:
    image: dasi0227/mcp-server-csdn:0.1.0
    container_name: mcp-server-csdn
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      TZ: ${TZ}
      CSDN_COOKIE: ${CSDN_COOKIE}
      ARTICLE_COVER_URL: ${CSDN_COVER_URL}
    networks:
      - ai-agent

  mcp-server-wecom:
    image: dasi0227/mcp-server-wecom:0.1.0
    container_name: mcp-server-wecom
    restart: unless-stopped
    ports:
      - "9002:9002"
    environment:
      TZ: ${TZ}
      AGENT_ID: ${WECOM_AGENT_ID}
      CORP_ID: ${WECOM_CORP_ID}
      CORP_SECRET: ${WECOM_CORP_SECRET}
    networks:
      - ai-agent

  mcp-server-amap:
    image: dasi0227/mcp-server-amap:0.1.0
    container_name: mcp-server-amap
    restart: unless-stopped
    ports:
      - "9003:9003"
    environment:
      TZ: ${TZ}
      API_KEY: ${AMAP_API_KEY}
    networks:
      - ai-agent

  # ===================== Tools =====================
  elasticsearch:
    image: elasticsearch:7.17.28
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - TZ=${TZ}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ai-agent

volumes:
  pgvector_data:
  mysql_data:
  redis_data:
  oneapi_data:
  elasticsearch_data:

networks:
  ai-agent:
    external: true
